# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_download_design.ui'
#
# Created: Sun Mar 13 13:51:06 2016
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_crawler_dialog(object):
    def setupUi(self, crawler_dialog):
        crawler_dialog.setObjectName(_fromUtf8("crawler_dialog"))
        crawler_dialog.resize(489, 594)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        crawler_dialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(crawler_dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_title = QtGui.QHBoxLayout()
        self.horizontalLayout_title.setObjectName(_fromUtf8("horizontalLayout_title"))
        self.label_2 = QtGui.QLabel(crawler_dialog)
        self.label_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_title.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(crawler_dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("icon.png")))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_title.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_title)
        self.line = QtGui.QFrame(crawler_dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.label_settings = QtGui.QLabel(crawler_dialog)
        self.label_settings.setObjectName(_fromUtf8("label_settings"))
        self.verticalLayout.addWidget(self.label_settings)
        self.checkBox_add_media = QtGui.QCheckBox(crawler_dialog)
        self.checkBox_add_media.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox_add_media.setChecked(True)
        self.checkBox_add_media.setObjectName(_fromUtf8("checkBox_add_media"))
        self.verticalLayout.addWidget(self.checkBox_add_media)
        self.horizontalLayout_add_options = QtGui.QHBoxLayout()
        self.horizontalLayout_add_options.setObjectName(_fromUtf8("horizontalLayout_add_options"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_add_options.addItem(spacerItem)
        self.verticalLayout_add_options = QtGui.QVBoxLayout()
        self.verticalLayout_add_options.setObjectName(_fromUtf8("verticalLayout_add_options"))
        self.horizontalLayout_add_options_mode = QtGui.QHBoxLayout()
        self.horizontalLayout_add_options_mode.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_add_options_mode.setObjectName(_fromUtf8("horizontalLayout_add_options_mode"))
        self.radioButton_extend = QtGui.QRadioButton(crawler_dialog)
        self.radioButton_extend.setChecked(True)
        self.radioButton_extend.setObjectName(_fromUtf8("radioButton_extend"))
        self.horizontalLayout_add_options_mode.addWidget(self.radioButton_extend)
        self.radioButton_overwrite = QtGui.QRadioButton(crawler_dialog)
        self.radioButton_overwrite.setObjectName(_fromUtf8("radioButton_overwrite"))
        self.horizontalLayout_add_options_mode.addWidget(self.radioButton_overwrite)
        self.radioButton_overwrite_empty = QtGui.QRadioButton(crawler_dialog)
        self.radioButton_overwrite_empty.setObjectName(_fromUtf8("radioButton_overwrite_empty"))
        self.horizontalLayout_add_options_mode.addWidget(self.radioButton_overwrite_empty)
        self.verticalLayout_add_options.addLayout(self.horizontalLayout_add_options_mode)
        self.checkBox_remove_broken = QtGui.QCheckBox(crawler_dialog)
        self.checkBox_remove_broken.setChecked(True)
        self.checkBox_remove_broken.setObjectName(_fromUtf8("checkBox_remove_broken"))
        self.verticalLayout_add_options.addWidget(self.checkBox_remove_broken)
        self.horizontalLayout_add_options.addLayout(self.verticalLayout_add_options)
        self.verticalLayout.addLayout(self.horizontalLayout_add_options)
        self.checkBox_download_missing = QtGui.QCheckBox(crawler_dialog)
        self.checkBox_download_missing.setChecked(True)
        self.checkBox_download_missing.setObjectName(_fromUtf8("checkBox_download_missing"))
        self.verticalLayout.addWidget(self.checkBox_download_missing)
        self.horizontalLayout_download_options = QtGui.QHBoxLayout()
        self.horizontalLayout_download_options.setObjectName(_fromUtf8("horizontalLayout_download_options"))
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_download_options.addItem(spacerItem1)
        self.verticalLayout_download_options = QtGui.QVBoxLayout()
        self.verticalLayout_download_options.setObjectName(_fromUtf8("verticalLayout_download_options"))
        self.checkBox_ignore_blacklist = QtGui.QCheckBox(crawler_dialog)
        self.checkBox_ignore_blacklist.setObjectName(_fromUtf8("checkBox_ignore_blacklist"))
        self.verticalLayout_download_options.addWidget(self.checkBox_ignore_blacklist)
        self.checkBox_redownload = QtGui.QCheckBox(crawler_dialog)
        self.checkBox_redownload.setObjectName(_fromUtf8("checkBox_redownload"))
        self.verticalLayout_download_options.addWidget(self.checkBox_redownload)
        self.horizontalLayout_download_options.addLayout(self.verticalLayout_download_options)
        self.verticalLayout.addLayout(self.horizontalLayout_download_options)
        self.line_5 = QtGui.QFrame(crawler_dialog)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.label_statistics = QtGui.QLabel(crawler_dialog)
        self.label_statistics.setObjectName(_fromUtf8("label_statistics"))
        self.verticalLayout.addWidget(self.label_statistics)
        self.tableWidget = QtGui.QTableWidget(crawler_dialog)
        self.tableWidget.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.label_status = QtGui.QLabel(crawler_dialog)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.verticalLayout.addWidget(self.label_status)
        self.progressBar = QtGui.QProgressBar(crawler_dialog)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.line_4 = QtGui.QFrame(crawler_dialog)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.verticalLayout_bottom_buttons = QtGui.QHBoxLayout()
        self.verticalLayout_bottom_buttons.setObjectName(_fromUtf8("verticalLayout_bottom_buttons"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_bottom_buttons.addItem(spacerItem2)
        self.pushButton_quit = QtGui.QPushButton(crawler_dialog)
        self.pushButton_quit.setAutoDefault(False)
        self.pushButton_quit.setFlat(False)
        self.pushButton_quit.setObjectName(_fromUtf8("pushButton_quit"))
        self.verticalLayout_bottom_buttons.addWidget(self.pushButton_quit)
        self.pushButton_stop = QtGui.QPushButton(crawler_dialog)
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.verticalLayout_bottom_buttons.addWidget(self.pushButton_stop)
        self.pushButton_start = QtGui.QPushButton(crawler_dialog)
        self.pushButton_start.setEnabled(True)
        self.pushButton_start.setCheckable(False)
        self.pushButton_start.setChecked(False)
        self.pushButton_start.setDefault(True)
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.verticalLayout_bottom_buttons.addWidget(self.pushButton_start)
        self.verticalLayout.addLayout(self.verticalLayout_bottom_buttons)

        self.retranslateUi(crawler_dialog)
        QtCore.QMetaObject.connectSlotsByName(crawler_dialog)

    def retranslateUi(self, crawler_dialog):
        crawler_dialog.setWindowTitle(QtGui.QApplication.translate("crawler_dialog", "Audio Downloader For Kanji Readings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-style:italic;\">Audio Downloader For Kanji Readings</span></p><p>Default values for below settings are displayed in parenthesis. Tooltips offer more information.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_settings.setText(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Run Settings</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_add_media.setToolTip(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p>Will modify the \'Audio\' field of the notes in the target deck to add audio files to the note.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_add_media.setText(QtGui.QApplication.translate("crawler_dialog", "Add media to cards (Yes)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_extend.setToolTip(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p>Will extend the Audio field with new entries, i.e. old entries are not lost.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_extend.setText(QtGui.QApplication.translate("crawler_dialog", "extend (Default)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_overwrite.setToolTip(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p>Will overwrite the Audio field with new sound files. If we don\'t have any new sound files, the field will remain untouched though.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_overwrite.setText(QtGui.QApplication.translate("crawler_dialog", "overwrite", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_overwrite_empty.setToolTip(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p>Will overwrite the Audio field with new sound files. If we don\'t have any new sound files, the field will be emptied.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_overwrite_empty.setText(QtGui.QApplication.translate("crawler_dialog", "overwrite even empty", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_remove_broken.setToolTip(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p>If this checkbox is checked then entries in the Audio field that point to media that does not exist anymore will be deleted.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_remove_broken.setText(QtGui.QApplication.translate("crawler_dialog", "Remove Broken Links (Yes)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_download_missing.setToolTip(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p>Download missing audio.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_download_missing.setText(QtGui.QApplication.translate("crawler_dialog", "Download missing audio (Yes)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ignore_blacklist.setToolTip(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p>The blacklist contains all readings to which we previously couldn\'t download any audio files. If this box is checked, we will try again.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ignore_blacklist.setText(QtGui.QApplication.translate("crawler_dialog", "ignore blacklist (No)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_redownload.setToolTip(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p>Download audio files for every reading again (even if audio files for some readings are already in the media folder).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_redownload.setText(QtGui.QApplication.translate("crawler_dialog", "redownload all (No)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_statistics.setText(QtGui.QApplication.translate("crawler_dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Run Statistics</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("crawler_dialog", "Total notes", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("crawler_dialog", "Total audio files", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("crawler_dialog", "Missing audio files", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("crawler_dialog", "Newly downloaded audio files", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("crawler_dialog", "Failed to download audio files", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("crawler_dialog", "Count", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_status.setText(QtGui.QApplication.translate("crawler_dialog", "Status: Idle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_quit.setText(QtGui.QApplication.translate("crawler_dialog", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_stop.setText(QtGui.QApplication.translate("crawler_dialog", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_start.setText(QtGui.QApplication.translate("crawler_dialog", "Start", None, QtGui.QApplication.UnicodeUTF8))

